# Generated by Django 4.1.3 on 2022-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0002_cryptonews_crypto_description_crypto_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuser',
            name='likes',
            field=models.ManyToManyField(related_name='like_cryptos', to='cryptos.crypto'),
        ),
        migrations.AddField(
            model_name='scuser',
            name='subscribes',
            field=models.ManyToManyField(related_name='sub_cryptos', to='cryptos.crypto'),
        ),
    ]
