# Generated by Django 4.1.3 on 2022-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_scuser_likes_scuser_subscribes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
