# Generated by Django 4.1.3 on 2022-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='news/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='crypto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='image',
            field=models.ImageField(null=True, upload_to='cryptos/'),
        ),
    ]
