# Generated by Django 4.1.3 on 2022-12-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0004_cryptonews_created_at_cryptonews_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='circulating_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crypto',
            name='market_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crypto',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
